# active spring boot profile

# spring common configuration
spring:
   profiles:
      active: dev
      
   # devtools - live reload
   devtools:
      livereload:
         enabled: true
   
   # mvc
   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
   web:
      resources:
         static-locations: file:/mysite-uploads/, classpath:/static/

   # message resource(i18n)
   messages:
      always-message-format: true
      basename: messages/messages_ko
      encoding: utf-8
   
   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 10MB
         max-request-size: 50MB
         
   # aop(@EnableAspectJAutoProxy)
   aop:
      auto: true
      proxy-target-class: true
      
---
#
# dev profile configuration
#
spring:
   config:
      activate:
         on-profile: dev
         
   # datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.10.40:3306/webdb?charset=utf8
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

---
#
# production profile configuration
#
spring:
   config:
      activate:
         on-profile: production
         
   # datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.10.40:3306/webdb?charset=utf8
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20


---  
# mybatis configuration
mybatis:
   config-location: classpath:mybatis/configuration.xml


---
# server configuration
server:
   port: 8080
   servlet:
      context-path: /mysite06
      encoding:
         charset: utf-8
         enabled: true


---
# logging configuration
logging:
   config: classpath:logback.xml